# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aegis < Formula
  desc ""
  homepage "https://github.com/lucasloureiror/AegisPass"
  version "1.2.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lucasloureiror/AegisPass/releases/download/v1.2.1/AegisPass_Darwin_arm64.tar.gz"
      sha256 "22876aeda3a8375714fda741e712d93394f9c09ba4cea683c1ab666db4a1e7cf"

      def install
        bin.install "aegis"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lucasloureiror/AegisPass/releases/download/v1.2.1/AegisPass_Darwin_x86_64.tar.gz"
      sha256 "76affb03d1e5f6642956a18716faf364d7f6b6151e16bba70ed35c1a24771e1f"

      def install
        bin.install "aegis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucasloureiror/AegisPass/releases/download/v1.2.1/AegisPass_Linux_arm64.tar.gz"
      sha256 "3709c68c3cb44bb01591c70eec0c74d5715850114811b462ecb4c04ffe1e754a"

      def install
        bin.install "aegis"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lucasloureiror/AegisPass/releases/download/v1.2.1/AegisPass_Linux_x86_64.tar.gz"
      sha256 "b52ce80a48be24c72bedc1ae63cf6d4ff8f8f2b555e6ce8afc5b9edf9d8b317d"

      def install
        bin.install "aegis"
      end
    end
  end
end
