# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aegis < Formula
  desc ""
  homepage "https://github.com/lucasloureiror/AegisPass"
  version "1.2.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lucasloureiror/AegisPass/releases/download/v1.2.2/AegisPass_Darwin_arm64.tar.gz"
      sha256 "2403d04f0309c060235abce02d89eacf83bc93d0fec34eeeac07e7a2adf304ed"

      def install
        bin.install "aegis"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lucasloureiror/AegisPass/releases/download/v1.2.2/AegisPass_Darwin_x86_64.tar.gz"
      sha256 "58d5e4a44c7495759bf9253d9b2ce3637d2cdc39548cce3960a347e3482f8996"

      def install
        bin.install "aegis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lucasloureiror/AegisPass/releases/download/v1.2.2/AegisPass_Linux_x86_64.tar.gz"
      sha256 "f83e7437ce0788e6300cb53167f399124f9a7c5d9650b26af3bacf6c9e96483c"

      def install
        bin.install "aegis"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucasloureiror/AegisPass/releases/download/v1.2.2/AegisPass_Linux_arm64.tar.gz"
      sha256 "17d16fe0d54b900e8e3c2929ad472d631a9dd990bf3d86148ab56bd2ebd42206"

      def install
        bin.install "aegis"
      end
    end
  end
end
