# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slh < Formula
  desc ""
  homepage "https://github.com/lucasloureiror/slh"
  version "0.5.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lucasloureiror/slh/releases/download/v0.5.3/slh_Darwin_arm64.tar.gz"
      sha256 "4953cae6fd5f43a6861cc9871fa42fefac3e1a31925e8d755bfe21011780e7a2"

      def install
        bin.install "slh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lucasloureiror/slh/releases/download/v0.5.3/slh_Darwin_x86_64.tar.gz"
      sha256 "3ecc3aa74f0aa10943d7737383967e845360ec0fdeeb6de23af66f41c0190f48"

      def install
        bin.install "slh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucasloureiror/slh/releases/download/v0.5.3/slh_Linux_arm64.tar.gz"
      sha256 "406f1b917d4b2a9990c7e04a0f3149160d99440e9eebf1bd7f8b452bf64fa4e7"

      def install
        bin.install "slh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lucasloureiror/slh/releases/download/v0.5.3/slh_Linux_x86_64.tar.gz"
      sha256 "12831fc7d664bad08a961ea1eb63366a6f6639744d2fe8a2227572fb8fef7649"

      def install
        bin.install "slh"
      end
    end
  end
end
